### ISSUE TITLE
👷 Gradle version catalog format

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#703]
## 📝 Description

For improving developer experience while maintaining our Gradle version catalog and easily detect unused dependencies, we want to change its format as below:

```toml
# Before

[plugins.dokka]
id = "org.jetbrains.dokka"
version.ref = "dokka"

# After

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
```

## 🔗 Dependencies

This issue is blocked by the following items:

- [x] Publication of **IntelliJ IDEA 2024.2** fixing the issue [IDEA-316453](https://youtrack.jetbrains.com/issue/IDEA-316453).

## ✅ Checklist

- [x] 👷 Change the format of our version catalog.
- [x] ➖ Remove unused dependencies.
- [x] 📝 Update the unreleased changelog for this issue.
